Someup/frontend

.github/workflows/push-anothor-repo.yml
build.sh

배포할 개인 레포 주소: https://github.com/qaws7791/someup-frontend
맞게 했는지 모르겠네요 확인 부탁드립니다

ci: 개인 레포로 배포하기 위한 github workflows 작성

---

.gitignore
.storybook/main.ts
.storybook/preview.ts
.vscode/settings.json
app/globals.css
app/layout.tsx
lib/utils/index.ts
package-lock.json
package.json
stories/Color.mdx
stories/Typography.mdx
styles/base.ts
styles/typography.ts
tailwind.config.ts

일단 typography와 colors부터 tailwind로 옮기고 storybook에 작성하였습니다

 typography, color tailwindcss 적용

---

components/icons/CloseOutlined.tsx
components/ui/Chip.tsx
stories/Chip.stories.tsx

chip 공통 컴포넌트 추가

---

lib/service/auth/universal.ts

액세스 토큰 이름을 refreshToken과 같이 카멜 케이스로 변경하면서 빠트린 부분 수정 했습니다

fix: getAccessTokenUniversal 함수에서 액세스 토큰 이름 수정

---

app/archive/page.tsx
components/archive/archive-list-item.tsx
components/archive/archive-list.tsx
components/archive/create-archive-dialog.tsx
components/archive/edit-archive-dialog.tsx
components/archive/remove-archive-dialog.tsx
components/icons/ThreeDotsFilled.tsx
components/ui/DropdownMenu.tsx
lib/service/archive/archive-queries.ts
lib/service/archive/archive-service.ts
lib/service/archive/use-archive-service.ts
package-lock.json
package.json
stories/DropdownMenu.stories.tsx
types/archive-types.ts

아카이브에 dropdown menu를 사용해 생성, 이름변경, 삭제

아카이브 페이지에 아카이브 리스트 추가

---

app/summary/[id]/page.tsx
app/write/[id]/page.tsx
components/post/post-detail.tsx
components/post/post-editor.tsx
components/post/url-text-field.tsx
components/summary/summary-save-button.tsx
lib/service/post/post-queries.ts
lib/service/post/post-service.ts
lib/service/post/use-post-service.ts
types/post-types.ts

- usePostDetail parameter type {id: string} -> id 로 변경하여 빌드 에러 수정하였습니다.
- /post -> /posts 로 엔드포인트 변경하였습니다.
- 요약 요청 후 게시글 보기 (status: draft), 저장 후 게시글 보기 (status: published) 처리 하였습니다.

build 오류 수정 및 API 수정

---

.github/workflows/build.yml
app/summary/[id]/layout.tsx
components/summary/feadback-box.tsx
components/ui/DropdownMenu.tsx
components/ui/Select.tsx
lib/env/client-env.ts

- 브랜치 푸시 시 빌드 프로세스 자동화를 위한 Github Actions 워크플로우 추가하였습니다
- .env 파일이 없어 빌드 에러나기 때문에 Zod 로 환경변수 검증 시 기본값을 설정하였습니다

build 워크 플로우 추가

---

components/ui/Button.tsx

rounded button에서 border radius가 제대로 적용이 안되는 문제가 있어서 수정했습니다.

fix: button 컴포넌트 base 스타일에서 rounded 삭제하고 각각 variant에서 적용하도록 변경

---

app/posts/[id]/layout.tsx
app/posts/[id]/page.tsx
components/post/delete-post-button.tsx
components/post/memo-text-field.tsx
components/post/post-detail.tsx
components/post/post-editor.tsx
components/post/post-tags.tsx
components/ui/TextField.tsx
lib/service/post/post-service.ts
lib/service/post/use-post-service.ts
types/post-types.ts

- 글 상세보기 페이지 구현하였습니다
- 태그 목록 보기, 수정 버튼 추가 및 수정 페이지로 이동, 삭제 버튼 추가 및 삭제 다이얼로그, 메모 등록/수정 기능 구현하였습니다

글 상세보기 페이지 구현

---

components/header/main-header.tsx

- Link 로 감싸고 cursor pointer 로 수정
- Fixes #43

fix: 로고 클릭하면 홈으로 이동하지 않는 이슈 해결

---

app/archive/archive-client.tsx
app/archive/page.tsx
components/post/post-list.tsx
lib/service/post/post-service.ts
types/post-types.ts

archiveId  기본값으로 0 대신 undefined로 넘어가도록 수정 ㅜㅜ

fix: archiveId 타입 number로 변경, 기본 값 삭제

---

components/post/url-text-field.tsx

- url 정규표현식 완화하고, alert 대신 Dialog 로 변경
- Fixes #40

fix: url 유효성 검사 수정

---

components/post/memo-text-field.tsx
lib/service/post/post-service.ts
lib/service/post/use-post-service.ts

Fixes #54
- post/patch -> post 로 통합

fix: 메모 추가/수정하기 api 수정

---

components/post/post-editor.tsx
components/post/post-save-dialog.tsx

- 아카이브 아이디 지정하여 페이지 전환하도록 수정하였습니다.
- 저장하기, 저장완료 버튼 사이즈 수정하였습니다. Fixes #61

Fix/61 archive 지정하여 저장 시 아카이브로 이동하지 않는 이슈 수정

---

components/archive/archive-list-item.tsx
components/archive/archive-list.tsx
lib/service/archive/constraints.ts

#50
- 아카이브 목록에서 이름이 길어질 경우 말줄임(...)으로 표시
- 2글자 제한이 없어짐으로 인해 수정 완료 시 0글자면 아카이브 이름 업데이트를 하지 않음
- input maxLength로 최대 길이를 초과하는 입력을 받지 않도록 변경

아카이브 목록 말줄임 표시 및 수정 시 유효성 검사 업데이트

---

components/archive/archive-list.tsx
components/archive/create-archive-dialog.tsx
lib/service/archive/constraints.ts
package-lock.json
package.json

#58 
- hook-form을 사용하여 폼 관리
- 에러 메시지 표시

아카이브 생성 다이얼로그 유효성 검사 및 에러 메시지 표시

---

components/post/url-text-field.tsx
components/ui/Dialog.tsx

요약 요청 실패 시 요약을 생성하는 데 문제가 발생했습니다. URL을 다시 확인하거나 잠시 후 다시 시도해 주세요. 메세지 표시 줄바꿈 인식할 수 있도록 DialogContent 에 white-space: pre-wrap 적용하여 줄바꿈 문자(\n)를 그대로 인식하여 줄바꿈될 수 있도록 함
Fixes #73

feat: 요약 요청 에러 발생 시 alert

---

components/ui/spinner.tsx
stories/Spinner.stories.tsx
tailwind.config.ts

Tailwind CSS의 커스텀 애니메이션을 사용하여 애니메이션 스피너를 구현
tailwind.config.js에서 키프레임과 애니메이션을 정의
Fixes #41

feat: loading spinner 구현

---

components/header/main-header.tsx

루트 경로가 아닌 main-header에 그림자 적용

---

app/posts/[id]/page.tsx
app/result/[id]/page.tsx
components/editor/editor.tsx
components/summary/feadback-box.tsx
components/summary/summary-save-button.tsx
components/ui/spinner.tsx

- prefetch 하는 동안 Spinner 가 표시되고
- editor component 를 dynamic import 하는 동안 Spinner 표시되도록 하였습니다
- Spinner 에 showText boolean props 를 추가하여 잠시만 기다려주세요 text 가 보여질지 말지 설정할 수 있도록 하였습니다

feat: 게시물/요약결과 보기 시 loading spinner 표시

---

components/auth/withdraw-dialog.tsx
components/user/user-button.tsx
lib/service/auth/auth-service.ts
lib/service/auth/user-auth-service.ts

헤더의 프로필 팝오버에서 회원탈퇴 클릭 시 회원탈퇴 모달 표시

회원탈퇴 기능 추가

---

app/archive/archive-client.tsx

#85 
존재하지 않는 아카이브 페이지를 보지 않도록 페이지 이동

fix: 잘못된 아카이브를 보고 있을 때 기본 페이지(/archive)로 이동

---

lib/service/post/use-post-service.ts

fix: 요약본 수정 후 쿼리 무효화

---

components/post/url-text-field.tsx
lib/service/post/use-post-service.ts
types/post-types.ts

fix: 요약 재요청 후 다시 fetch 되지 않는 이슈

---

components/post/post-editor.tsx
components/post/url-text-field.tsx
components/summary/feadback-box.tsx

- 재요약 요청시, 요약 옵션 설정 시, 저장하기 시 로그인 안되어있을 경우 LoginDialog 호출

fix: 로그인 분기 처리 추가

---

components/archive/remove-archive-dialog.tsx

해당 아카이브에 저장된 요약본들은 모두 삭제됩니다 -> 해당 아카이브에 저장된 요약본들은 사라지지 않습니다

feat: 아카이브 삭제 다이얼로그 문구 변경

---

components/header/main-header.tsx

about 페이지 push 한다는 게 메인에 해버렸네요. 같이 확인해주세요

header 컴포넌트 about 페이지 연결
